version: 2

sources:
  - name: jaffle_shop
    description: This is the raw database populated from S3
    database: raw
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _etl_loaded_at

    tables:
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.
        columns:
          - name: id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null      
          - name: status
            description: Note that the status can change over time                
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}

      - name: customers # this will use the freshness defined above
      - name: customers_deletes

        freshness: null # do not check freshness for this table
  - name: stripe
    tables:
      - name: payments        

  - name: Utils
    database: Tools
    tables:
      - name: Constants        
      - name: Constants_Pivoted  